openapi: 3.0.3
info:
  title: Gilmore's Glorious Goods
  version: 0.0.1
paths: 
        
  /products:
    get:
      summary: Get product list
      description: Returns a list of products that can be filtered, sorted and paged
      tags:
        - service 1
      parameters:
        - $ref: '#/components/parameters/Sorting'
        - $ref: '#/components/parameters/Filtering'
        - $ref: '#/components/parameters/Paging'
      responses:
        '200':
          description: Successful operation. Returns an array of products.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ProductList'
        '405':
          description: Validation exception
    patch:
      summary: Update a product
      description: Updates an existing product by its Id
      tags:
        - service 1
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '405':
          description: Validation exception
    post:
      summary: Add a new product 
      description: Creates and adds a new product
      tags:
        - service 1
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '405':
          description: Validation exception

          
  /products/{id}:
    get:
      summary: Find product by ID
      description: Returns a single product by its ID
      tags:
        - service 1
      parameters:
        - name: id
          in: path
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
     
    delete:
      summary: Remove product by ID
      description: Deletes a product by its ID
      tags:
        - service 1
      parameters:
        - name: id
          in: path
          description: ID of product listing to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found          
    
  /products/unit-of-measure/{unitOfMeasure}:
    delete:
      summary: Delete products by unit of measure
      description: Deletes every product that uses a specified unit of measure
      tags:
        - service 1
      parameters:
        - name: unitOfMeasure
          in: path
          description: Unit of measure to match
          required: true
          schema:
            $ref: '#/components/schemas/UnitOfMeasure'
      responses:
        '200':
          description: Successful operation. Returns a number of products deleted
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Count'
        '405':
          description: Validation exception
    
  /products/unit-of-measure/{unitOfMeasure}/countGreater:
    get:
      summary: Count products which exeed unit of measure
      description: Count products with a greater unit of measure value than the one specified
      tags:
        - service 1
      parameters:
        - name: unitOfMeasure
          in: path
          description: Unit of measure value to exceed
          required: true
          schema:
            $ref: '#/components/schemas/UnitOfMeasure'
      responses:
        '200':
          description: Successful operation. Returns product count
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Count'
        '405':
          description: Validation exception    
          
  /products/manufacture-cost/{manufactureCost}/count:
    get:
      summary: Count products with set manufacture cost
      description: Count products that match a specified manufacture cost
      tags:
        - service 1
      parameters:
        - name: manufactureCost
          in: path
          description: Manufacture cost to match
          required: true
          schema:
            $ref: '#/components/schemas/ManufactureCost'
      responses:
        '200':
          description: Successful operation. Returns product count
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Count'
        '405':
          description: Validation exception

    
  /ebay/filter/price/{price-from}/{price-to}:
    get:
      summary: Get products in a price range
      description: Returns a list of products that fall in a specified price range
      tags:
        - service 2
      parameters:
        - name: price-from
          in: path
          description: Lowest price
          required: true
          schema:
            $ref: '#/components/schemas/Price'
        - name: price-to
          in: path
          description: Highest price
          required: true
          schema:
            $ref: '#/components/schemas/Price'
      responses:
        '200':
          description: Successful operation. Returns an array of products.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ProductList'
        '405':
          description: Validation exception
     
  /ebay/price/decrease/{decrease-percent}:
    post:
      summary: Decrease every product's price
      description: Decreases the price of every product by a specified amount, in percentages 
      tags:
        - service 2
      parameters:
        - name: decrease-percent
          in: path
          description: Decrease percent
          required: true
          schema:
            type: number
            format: float
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: Successful operation
        '405':
          description: Validation exception

components:
  schemas:
    
    Product:
      type: object
      properties: 
        id: 
          type: integer
          format: int64
          minimum: 1
          example: 42
        name: 
          type: string
          example: Merchandise
        coordinates: 
          $ref: '#/components/schemas/Coordinates'
        creationDate: 
          type: string
          nullable: false
          format: date
        price: 
          $ref: '#/components/schemas/Price'
        manufactureCost: 
          $ref: '#/components/schemas/ManufactureCost'
        unitOfMeasure:
          $ref: '#/components/schemas/UnitOfMeasure'
        manufacturerId: 
          type: integer
          nullable: true
          format: int64
          minimum: 1
          example: 42
      
    ManufactureCost:
      type: number
      format: float
      example: 3.50
      
    Price:
      type: integer
      format: int64
      example: 150
      
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'
     
    Coordinates:
      type: object
      nullable: false
      properties:
        x: 
          type: integer
          format: int64
          example: 45
        y: 
          type: integer
          format: int64
          maximum: 716
          example: 15
     
    Organization:
      type: object
      nullable: true
      properties:
        id: 
          type: integer
          format: int64
          minimum: 1
          example: 42
        name: 
          type: string
        fullName: 
          type: string
        annualTurnover: 
          type: number
          format: float
        employeesCount: 
          type: integer
          format: int64
        postalAddress: 
          $ref: '#/components/schemas/Address'
     
    Address:
      type: object
      properties:
        zipCode: 
          type: string
        town:
          $ref: '#/components/schemas/Location'
      
    Location:
      type: object
      nullable: true
      properties:
        x:
          type: number
          format: double
        y:
          type: number
          format: double
        z: 
          type: number
          format: float
        name: 
          type: string
          nullable: true
          maxLength: 909
     
    UnitOfMeasure:
      type: string
      nullable: true
      enum:
        - KILOGRAMS
        - CENTIMETERS
        - LITERS
        - GRAMS
      
    Count:
      type: integer
      example: 13
    
    
  parameters:
   
    Sorting:
      name: sort
      in: query
      description: Property and order to sort the list by
      required: false
      explode: true
      schema:
        type: object
        properties:
          by:
            type: string
            example: 'price'
          order:
            type: string
            enum:
              - ASCENDING
              - DESCENDING
      
    Filtering:
      name: filters
      in: query
      description: Array of filters 
      required: false
      explode: true
      schema:
        type: array
        items:
          type: object
          properties:
            property:
              type: string
            filter:
              type: string
              
    Paging:
      name: paging
      in: query
      description: Page size and index
      required: false
      explode: true
      schema:
        type: object
        properties:
          size:
            type: integer
            minimum: 1
            example: 20
          index:
            type: integer
            minimum: 0